meta_product_name: "Antoine STAUMONT"
meta_title: "Antoine STAUMONT - CV"
meta_description: "Bienvenue sur mon site afin de mieux me connaitre."
meta_image: "antoine.jpg" # should exist in `app/assets/images/`

